### ISSUE TITLE
PAS installation fails with "giving up" error

### ISSUE THREAD

**Issue by arbulu89** [SUSE/ha-sap-terraform-deployments#473]
SAP Netweaver PAS installation fails after trying to start the `disp-work` process during 10 minutes. I have seen this error in Azure and GCP at least.

We need to research to find out why this is happening. Some possible issues:
- Machine type is too small
- We are overusing CPU somewhere else
- We are doing something wrong with memory or disk (swap?)

```
19.05.2020 08:11:22
GetProcessList
OK
name, description, dispstatus, textstatus, starttime, elapsedtime, pid
disp+work, Dispatcher, YELLOW, Server startup procedure running, 2020 05 19 08:01:11, 0:10:11, 25279
igswd_mt, IGS Watchdog, GREEN, Running, 2020 05 19 08:01:11, 0:10:11, 25280
gwrd, Gateway, GREEN, Running, 2020 05 19 08:01:12, 0:10:10, 25284
icman, ICM, GREEN, Running, 2020 05 19 08:01:12, 0:10:10, 25285
module.netweaver_node.module.netweaver_provision.null_resource.provision[2] (remote-exec): [INFO    ]
ERROR      2020-05-19 08:11:22.016 (root/sapinst) (startInstallation) [iaxxbjsmod.cpp:83] id=nw.progress.waitingForStartABAPFailed errno=CJS-30149
ABAP processes of instance HA1/D01 [ABAP: STARTING] did not start after 10:10 minutes. Giving up.
module.netweaver_node.module.netweaver_provision.null_resource.provision[2] (remote-exec): [INFO    ]
ERROR      2020-05-19 08:11:22.398 (root/sapinst) (startInstallation) [CSiStepExecute.cpp:1104] id=controller.stepExecuted errno=FCO-00011 CSiStepExecute::execute()
The step start with step key |NW_ABAP_CI|ind|ind|ind|ind|0|0|NW_CI_Instance|ind|ind|ind|ind|ci|0|NW_CI_Instance_Start|ind|ind|ind|ind|42|0|start was executed with status ERROR (Last error reported by the step: ABAP processes of instance HA1/D01 [ABAP: STARTING] did not start after 10:10 minutes. Giving up).
```

**Comment by MalloZup** [comment]
@arbulu89  I think we fixed this I didn't have such issue.

I'm closing feel free to reopen in case contrary

**Comment by arbulu89** [comment]
@MalloZup This issue is not fixed. Having merged PRs is just a coincidence

**Comment by yeoldegrove** [comment]
What I have seen in the past is, that depending on the sizing and disk speed of the HANA and Netweaver VMs, one might run into issues like this. There is really no fix for this other than using sufficient sizing.
